### ISSUE TITLE
Missing female villager names translation in Jade tooltip

### ISSUE THREAD

**Issue by WenXin20** [Daripher/Female-Villagers#4]
```
Minecraft v1.19.2
Female Villagers v1.4
```

Female entities are missing lang

![2023-02-19_22 14 40](https://user-images.githubusercontent.com/12000593/220008245-0adb7c01-d6fd-48f5-bbcc-608ea2b3eb18.png)

**Comment by Daripher** [comment]
This is strange, other mobs have their names displayed. This is Jade mod, am I right?

**Comment by WenXin20** [comment]
Oh yes, it is Jade

**Comment by Aceplante** [comment]
This also applies to when you pick them up with carry on
