### ISSUE TITLE
java.lang.IllegalArgumentException: Failed to create model for ad_astra:lunarian

### ISSUE THREAD

**Issue by TrisRV** [Daripher/Female-Villagers#5]
The newest version seems to have some conflict with Ad Astra villager textures
java.lang.IllegalArgumentException: Failed to create model for ad_astra:lunarian

Its only with the 1.5 versions, if I downgrade to the 1.4a the game doesn't crash anymore.

**Comment by Daripher** [comment]
This was fixed in version 1.5a
