### ISSUE TITLE
Male villagers change gender when respawned

### ISSUE THREAD

**Issue by son0fether** [Daripher/Female-Villagers#7]
Hi there.  Thank you for making this mod.

We've found a compatibility issue for this mod with mods like Carry On and capture cells/pokeballs.  If you pick up a regular (male) Villager with a Capture Cell, some pokeball mod, or Carry On or similar, and place it down again, it experiences the game hooks that trigger the 50/50 convert and can get everything about it reset to a Female Villager (name, trade history, etc.).  This is true even for (male) Villagers that were spawned once this mod is running.

Any solution that would allow that conversion check to get skipped when the Villager entity is placed into the world repeatedly would work.  One solution could be adding a tag/nbt to existing villagers when they are loaded or checked for random conversion and to not retry the conversion for villagers with that tag.

I'm using the 1.19.2-1.6 mod version.
Here's a mod to try this with: https://www.curseforge.com/minecraft/mc-mods/portable-mobs
Shift-right click on a villager to pick them up.

This is a blocker for using this mod whenever any mod that can pick up and put back down a villager is in a pack.  Thanks for looking into this.

**Comment by xFirefalconx** [comment]
Thanks for the fix! Looking forward to the update :)

**Comment by Catomax262** [comment]
Same issue with Easy Villagers, females become males when turned into items, but when placed they have a chance to not be depleted and spawn a female one infinitely until the male one spawns

**Comment by V972** [comment]
^^^
having same issue on 1.18.2 with latest Easy Villager and Female Villagers
