### ISSUE TITLE
Chance to change to a female villager throught nether / each portal

### ISSUE THREAD

**Issue by Gods-Warrior** [Daripher/Female-Villagers#9]
Minecraft version 1.18.2

Whenever a villager go throught nether (any) portal then there is chance that the villager will change to a female villager.
In the case also all trades are reset but not prefession level - then if the villager was master then after "transformation" he has only 2 trades and can not be leveled up.
It looks that the problem is, that the tranformation process is started whenever a villager mob is created - which appear also when a villager go throught a portal to another dimension.

**Comment by Daripher** [comment]
Duplicate of #7
